// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package Files

import (
	"intelligent-course-aware-ide/api/Files"
)

type ControllerV1 struct{}

func NewV1() Files.IFilesV1 {
	return &ControllerV1{}
}
