// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalAssignmentUserFeedbackDao is an internal type for wrapping the internal DAO implementation.
type internalAssignmentUserFeedbackDao = *internal.AssignmentUserFeedbackDao

// assignmentUserFeedbackDao is the data access object for the table AssignmentUserFeedback.
// You can define custom methods on it to extend its functionality as needed.
type assignmentUserFeedbackDao struct {
	internalAssignmentUserFeedbackDao
}

var (
	// AssignmentUserFeedback is a globally accessible object for table AssignmentUserFeedback operations.
	AssignmentUserFeedback = assignmentUserFeedbackDao{
		internal.NewAssignmentUserFeedbackDao(),
	}
)

// Add your custom methods and functionality below.
