// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalAssignmentsDao is an internal type for wrapping the internal DAO implementation.
type internalAssignmentsDao = *internal.AssignmentsDao

// assignmentsDao is the data access object for the table assignments.
// You can define custom methods on it to extend its functionality as needed.
type assignmentsDao struct {
	internalAssignmentsDao
}

var (
	// Assignments is a globally accessible object for table assignments operations.
	Assignments = assignmentsDao{
		internal.NewAssignmentsDao(),
	}
)

// Add your custom methods and functionality below.
