// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// assignmentFilesDao is the data access object for the table AssignmentFiles.
// You can define custom methods on it to extend its functionality as needed.
type assignmentFilesDao struct {
	*internal.AssignmentFilesDao
}

var (
	// AssignmentFiles is a globally accessible object for table AssignmentFiles operations.
	AssignmentFiles = assignmentFilesDao{internal.NewAssignmentFilesDao()}
)

// Add your custom methods and functionality below.
