// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalChatmessageinfoDao is an internal type for wrapping the internal DAO implementation.
type internalChatmessageinfoDao = *internal.ChatmessageinfoDao

// chatmessageinfoDao is the data access object for the table chatmessageinfo.
// You can define custom methods on it to extend its functionality as needed.
type chatmessageinfoDao struct {
	internalChatmessageinfoDao
}

var (
	// Chatmessageinfo is a globally accessible object for table chatmessageinfo operations.
	Chatmessageinfo = chatmessageinfoDao{
		internal.NewChatmessageinfoDao(),
	}
)

// Add your custom methods and functionality below.
