// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// chatUserInfoDao is the data access object for the table ChatUserInfo.
// You can define custom methods on it to extend its functionality as needed.
type chatUserInfoDao struct {
	*internal.ChatUserInfoDao
}

var (
	// ChatUserInfo is a globally accessible object for table ChatUserInfo operations.
	ChatUserInfo = chatUserInfoDao{internal.NewChatUserInfoDao()}
)

// Add your custom methods and functionality below.
