// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalChatuserinfoDao is an internal type for wrapping the internal DAO implementation.
type internalChatuserinfoDao = *internal.ChatuserinfoDao

// chatuserinfoDao is the data access object for the table chatuserinfo.
// You can define custom methods on it to extend its functionality as needed.
type chatuserinfoDao struct {
	internalChatuserinfoDao
}

var (
	// Chatuserinfo is a globally accessible object for table chatuserinfo operations.
	Chatuserinfo = chatuserinfoDao{
		internal.NewChatuserinfoDao(),
	}
)

// Add your custom methods and functionality below.
