// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// chatMessageInfoDao is the data access object for the table ChatMessageInfo.
// You can define custom methods on it to extend its functionality as needed.
type chatMessageInfoDao struct {
	*internal.ChatMessageInfoDao
}

var (
	// ChatMessageInfo is a globally accessible object for table ChatMessageInfo operations.
	ChatMessageInfo = chatMessageInfoDao{internal.NewChatMessageInfoDao()}
)

// Add your custom methods and functionality below.
