// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalChatsDao is an internal type for wrapping the internal DAO implementation.
type internalChatsDao = *internal.ChatsDao

// chatsDao is the data access object for the table chats.
// You can define custom methods on it to extend its functionality as needed.
type chatsDao struct {
	internalChatsDao
}

var (
	// Chats is a globally accessible object for table chats operations.
	Chats = chatsDao{
		internal.NewChatsDao(),
	}
)

// Add your custom methods and functionality below.
