// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// chatsDao is the data access object for the table Chats.
// You can define custom methods on it to extend its functionality as needed.
type chatsDao struct {
	*internal.ChatsDao
}

var (
	// Chats is a globally accessible object for table Chats operations.
	Chats = chatsDao{internal.NewChatsDao()}
)

// Add your custom methods and functionality below.
