// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// commentsDao is the data access object for the table Comments.
// You can define custom methods on it to extend its functionality as needed.
type commentsDao struct {
	*internal.CommentsDao
}

var (
	// Comments is a globally accessible object for table Comments operations.
	Comments = commentsDao{internal.NewCommentsDao()}
)

// Add your custom methods and functionality below.
