// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// commentDao is the data access object for the table Comment.
// You can define custom methods on it to extend its functionality as needed.
type commentDao struct {
	*internal.CommentDao
}

var (
	// Comment is a globally accessible object for table Comment operations.
	Comment = commentDao{internal.NewCommentDao()}
)

// Add your custom methods and functionality below.
