// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalCoursesDao is an internal type for wrapping the internal DAO implementation.
type internalCoursesDao = *internal.CoursesDao

// coursesDao is the data access object for the table courses.
// You can define custom methods on it to extend its functionality as needed.
type coursesDao struct {
	internalCoursesDao
}

var (
	// Courses is a globally accessible object for table courses operations.
	Courses = coursesDao{
		internal.NewCoursesDao(),
	}
)

// Add your custom methods and functionality below.
