// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalCourseFilesDao is an internal type for wrapping the internal DAO implementation.
type internalCourseFilesDao = *internal.CourseFilesDao

// courseFilesDao is the data access object for the table CourseFiles.
// You can define custom methods on it to extend its functionality as needed.
type courseFilesDao struct {
	internalCourseFilesDao
}

var (
	// CourseFiles is a globally accessible object for table CourseFiles operations.
	CourseFiles = courseFilesDao{
		internal.NewCourseFilesDao(),
	}
)

// Add your custom methods and functionality below.
