// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// courseAssistantsDao is the data access object for the table CourseAssistants.
// You can define custom methods on it to extend its functionality as needed.
type courseAssistantsDao struct {
	*internal.CourseAssistantsDao
}

var (
	// CourseAssistants is a globally accessible object for table CourseAssistants operations.
	CourseAssistants = courseAssistantsDao{internal.NewCourseAssistantsDao()}
)

// Add your custom methods and functionality below.
