// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalCoursefilesDao is an internal type for wrapping the internal DAO implementation.
type internalCoursefilesDao = *internal.CoursefilesDao

// coursefilesDao is the data access object for the table coursefiles.
// You can define custom methods on it to extend its functionality as needed.
type coursefilesDao struct {
	internalCoursefilesDao
}

var (
	// Coursefiles is a globally accessible object for table coursefiles operations.
	Coursefiles = coursefilesDao{
		internal.NewCoursefilesDao(),
	}
)

// Add your custom methods and functionality below.
