// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// filesDao is the data access object for the table Files.
// You can define custom methods on it to extend its functionality as needed.
type filesDao struct {
	*internal.FilesDao
}

var (
	// Files is a globally accessible object for table Files operations.
	Files = filesDao{internal.NewFilesDao()}
)

// Add your custom methods and functionality below.
