// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalFuzzySearchAdvDao is an internal type for wrapping the internal DAO implementation.
type internalFuzzySearchAdvDao = *internal.FuzzySearchAdvDao

// fuzzySearchAdvDao is the data access object for the table fuzzy_search_adv.
// You can define custom methods on it to extend its functionality as needed.
type fuzzySearchAdvDao struct {
	internalFuzzySearchAdvDao
}

var (
	// FuzzySearchAdv is a globally accessible object for table fuzzy_search_adv operations.
	FuzzySearchAdv = fuzzySearchAdvDao{
		internal.NewFuzzySearchAdvDao(),
	}
)

// Add your custom methods and functionality below.
