// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalLecturesDao is an internal type for wrapping the internal DAO implementation.
type internalLecturesDao = *internal.LecturesDao

// lecturesDao is the data access object for the table Lectures.
// You can define custom methods on it to extend its functionality as needed.
type lecturesDao struct {
	internalLecturesDao
}

var (
	// Lectures is a globally accessible object for table Lectures operations.
	Lectures = lecturesDao{
		internal.NewLecturesDao(),
	}
)

// Add your custom methods and functionality below.
