// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// lectureFilesDao is the data access object for the table LectureFiles.
// You can define custom methods on it to extend its functionality as needed.
type lectureFilesDao struct {
	*internal.LectureFilesDao
}

var (
	// LectureFiles is a globally accessible object for table LectureFiles operations.
	LectureFiles = lectureFilesDao{internal.NewLectureFilesDao()}
)

// Add your custom methods and functionality below.
