// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalLectureNoteFilesDao is an internal type for wrapping the internal DAO implementation.
type internalLectureNoteFilesDao = *internal.LectureNoteFilesDao

// lectureNoteFilesDao is the data access object for the table LectureNoteFiles.
// You can define custom methods on it to extend its functionality as needed.
type lectureNoteFilesDao struct {
	internalLectureNoteFilesDao
}

var (
	// LectureNoteFiles is a globally accessible object for table LectureNoteFiles operations.
	LectureNoteFiles = lectureNoteFilesDao{
		internal.NewLectureNoteFilesDao(),
	}
)

// Add your custom methods and functionality below.
