// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// lecutreNoteFilesDao is the data access object for the table LecutreNoteFiles.
// You can define custom methods on it to extend its functionality as needed.
type lecutreNoteFilesDao struct {
	*internal.LecutreNoteFilesDao
}

var (
	// LecutreNoteFiles is a globally accessible object for table LecutreNoteFiles operations.
	LecutreNoteFiles = lecutreNoteFilesDao{internal.NewLecutreNoteFilesDao()}
)

// Add your custom methods and functionality below.
