// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// sharedFilePartnersDao is the data access object for the table SharedFilePartners.
// You can define custom methods on it to extend its functionality as needed.
type sharedFilePartnersDao struct {
	*internal.SharedFilePartnersDao
}

var (
	// SharedFilePartners is a globally accessible object for table SharedFilePartners operations.
	SharedFilePartners = sharedFilePartnersDao{internal.NewSharedFilePartnersDao()}
)

// Add your custom methods and functionality below.
