// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// sharedFileContentsDao is the data access object for the table SharedFileContents.
// You can define custom methods on it to extend its functionality as needed.
type sharedFileContentsDao struct {
	*internal.SharedFileContentsDao
}

var (
	// SharedFileContents is a globally accessible object for table SharedFileContents operations.
	SharedFileContents = sharedFileContentsDao{internal.NewSharedFileContentsDao()}
)

// Add your custom methods and functionality below.
