// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// sharedFileOperationsDao is the data access object for the table SharedFileOperations.
// You can define custom methods on it to extend its functionality as needed.
type sharedFileOperationsDao struct {
	*internal.SharedFileOperationsDao
}

var (
	// SharedFileOperations is a globally accessible object for table SharedFileOperations operations.
	SharedFileOperations = sharedFileOperationsDao{internal.NewSharedFileOperationsDao()}
)

// Add your custom methods and functionality below.
