// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// sharedTasksDao is the data access object for the table SharedTasks.
// You can define custom methods on it to extend its functionality as needed.
type sharedTasksDao struct {
	*internal.SharedTasksDao
}

var (
	// SharedTasks is a globally accessible object for table SharedTasks operations.
	SharedTasks = sharedTasksDao{internal.NewSharedTasksDao()}
)

// Add your custom methods and functionality below.
