// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// sharedFilesDao is the data access object for the table SharedFiles.
// You can define custom methods on it to extend its functionality as needed.
type sharedFilesDao struct {
	*internal.SharedFilesDao
}

var (
	// SharedFiles is a globally accessible object for table SharedFiles operations.
	SharedFiles = sharedFilesDao{internal.NewSharedFilesDao()}
)

// Add your custom methods and functionality below.
