// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// testcaseAndAnswerFilesDao is the data access object for the table TestcaseAndAnswerFiles.
// You can define custom methods on it to extend its functionality as needed.
type testcaseAndAnswerFilesDao struct {
	*internal.TestcaseAndAnswerFilesDao
}

var (
	// TestcaseAndAnswerFiles is a globally accessible object for table TestcaseAndAnswerFiles operations.
	TestcaseAndAnswerFiles = testcaseAndAnswerFilesDao{internal.NewTestcaseAndAnswerFilesDao()}
)

// Add your custom methods and functionality below.
