// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalUserfileinfoDao is an internal type for wrapping the internal DAO implementation.
type internalUserfileinfoDao = *internal.UserfileinfoDao

// userfileinfoDao is the data access object for the table userfileinfo.
// You can define custom methods on it to extend its functionality as needed.
type userfileinfoDao struct {
	internalUserfileinfoDao
}

var (
	// Userfileinfo is a globally accessible object for table userfileinfo operations.
	Userfileinfo = userfileinfoDao{
		internal.NewUserfileinfoDao(),
	}
)

// Add your custom methods and functionality below.
