// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// userFileInfoDao is the data access object for the table UserFileInfo.
// You can define custom methods on it to extend its functionality as needed.
type userFileInfoDao struct {
	*internal.UserFileInfoDao
}

var (
	// UserFileInfo is a globally accessible object for table UserFileInfo operations.
	UserFileInfo = userFileInfoDao{internal.NewUserFileInfoDao()}
)

// Add your custom methods and functionality below.
