// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"intelligent-course-aware-ide/internal/dao/internal"
)

// internalUserCourseInfoDao is an internal type for wrapping the internal DAO implementation.
type internalUserCourseInfoDao = *internal.UserCourseInfoDao

// userCourseInfoDao is the data access object for the table UserCourseInfo.
// You can define custom methods on it to extend its functionality as needed.
type userCourseInfoDao struct {
	internalUserCourseInfoDao
}

var (
	// UserCourseInfo is a globally accessible object for table UserCourseInfo operations.
	UserCourseInfo = userCourseInfoDao{
		internal.NewUserCourseInfoDao(),
	}
)

// Add your custom methods and functionality below.
