// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package assignment

import (
	"intelligent-course-aware-ide/api/assignment"
	assignmentLogic "intelligent-course-aware-ide/internal/logic/assignment"
	assignmentFeebackLogic "intelligent-course-aware-ide/internal/logic/assignmentFeedback"
	courseLogic "intelligent-course-aware-ide/internal/logic/course"
	fileLogic "intelligent-course-aware-ide/internal/logic/file"
	testcaseAndAnswerLogic "intelligent-course-aware-ide/internal/logic/testcaseAndAnswer"
)

type ControllerV1 struct {
	assignments         *assignmentLogic.Assignments
	files               *fileLogic.Files
	testcaseAndAnswers  *testcaseAndAnswerLogic.TestcaseAndAnswers
	courses             *courseLogic.Courses
	assignmentFeedbacks *assignmentFeebackLogic.Assignmentfeebacks
}

func NewV1() assignment.IAssignmentV1 {
	return &ControllerV1{
		assignments:         assignmentLogic.New(),
		files:               fileLogic.New(),
		testcaseAndAnswers:  testcaseAndAnswerLogic.New(),
		courses:             courseLogic.New(),
		assignmentFeedbacks: assignmentFeebackLogic.New(),
	}
}
