// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package assignment

import (
	"intelligent-course-aware-ide/api/assignment"
	assignmentLogic "intelligent-course-aware-ide/internal/logic/assignment"
	courseLogic "intelligent-course-aware-ide/internal/logic/course"
)

type ControllerV1 struct {
	assignments *assignmentLogic.Assignments
	courses     *courseLogic.Courses
}

func NewV1() assignment.IAssignmentV1 {
	return &ControllerV1{
		assignments: assignmentLogic.New(),
		courses:     courseLogic.New(),
	}
}
