// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package assignment

import (
	"intelligent-course-aware-ide/api/assignment"
)

type ControllerV1 struct{}

func NewV1() assignment.IAssignmentV1 {
	return &ControllerV1{}
}
