// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package command2

import (
	"intelligent-course-aware-ide/api/command2"
)

type ControllerV1 struct{}

func NewV1() command2.ICommand2V1 {
	return &ControllerV1{}
}
