services:
  app:
    build:
      context: ./intelligent-course-aware-ide
      dockerfile: ../Dockerfiles/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/usr/Document
      - ./log:/usr/log
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - runner
      - database
    networks:
      - backend-net

  runner:
    build:
      context: ./
      dockerfile: ./Dockerfiles/runner/Dockerfile
    volumes:
      - ./data:/usr/Document
    networks:
      - backend-net

  database:
    build:
      context: ./
      dockerfile: ./Dockerfiles/database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
