SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Files;
DROP TABLE IF EXISTS CourseFiles;
CREATE TABLE Files (
    fileId BIGINT AUTO_INCREMENT PRIMARY KEY,
    fileSize BIGINT NOT NULL,
    fileUrl TEXT NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    fileType VARCHAR(50) NOT NULL,
    uploaderId BIGINT,
    uploadDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastModified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (uploaderId) REFERENCES Users(userId)
);
CREATE TABLE CourseFiles(
    fileId BIGINT NOT NULL,
    courseId BIGINT NOT NULL,
    PRIMARY KEY (fileId, courseId),
    FOREIGN KEY (fileId) REFERENCES Files(fileId),
    FOREIGN KEY (courseId) REFERENCES Courses(courseId)
);
SET FOREIGN_KEY_CHECKS = 1;