// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package task

import (
	"intelligent-course-aware-ide/api/task"
)

type ControllerV1 struct{}

func NewV1() task.ITaskV1 {
	return &ControllerV1{}
}
