// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package runner

import (
	"intelligent-course-aware-ide/api/runner"
	runnerLogic "intelligent-course-aware-ide/internal/logic/runner"
)

type ControllerV1 struct {
	runners *runnerLogic.Runners
}

func NewV1() runner.IRunnerV1 {
	return &ControllerV1{
		runners: runnerLogic.New(),
	}
}
