// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package lecture

import (
	"intelligent-course-aware-ide/api/lecture"
	courseLogic "intelligent-course-aware-ide/internal/logic/course"
	loginLogic "intelligent-course-aware-ide/internal/logic/login"
)

type ControllerV1 struct {
	courses *courseLogic.Courses
	logins  *loginLogic.Logins
}

func NewV1() lecture.ILectureV1 {
	return &ControllerV1{
		courses: courseLogic.New(),
		logins:  loginLogic.New(),
	}
}
