// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sharedFile

import (
	"intelligent-course-aware-ide/api/sharedFile"
)

type ControllerV1 struct{}

func NewV1() sharedFile.ISharedFileV1 {
	return &ControllerV1{}
}
