// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"intelligent-course-aware-ide/api/user"
	userLogic "intelligent-course-aware-ide/internal/logic/user"
)

type ControllerV1 struct {
	users *userLogic.Users
}

func NewV1() user.IUserV1 {
	return &ControllerV1{
		users: userLogic.New(),
	}
}
