// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"context"
	"errors"
	"intelligent-course-aware-ide/internal/dao"
	"intelligent-course-aware-ide/internal/model/entity"
)

func CheckUserHasPermssion(ctx context.Context, UserToDeleteId int64, userId int64) (success bool, err error) {
	var userToDelete *entity.Users
	err = dao.Users.Ctx(ctx).WherePri(UserToDeleteId).Scan(&userToDelete)
	if err != nil || userToDelete == nil {
		return false, errors.New("maybe it is because user to delete not found")
	}

	var user *entity.Users
	err = dao.Users.Ctx(ctx).WherePri(userId).Scan(&user)
	if err != nil || user == nil {
		return false, errors.New("maybe it is because user not found")
	}

	if user.UserId == userToDelete.UserId || (user.Identity == "superuser" && userToDelete.Identity != "superuser") {
		return true, nil
	} else {
		return false, errors.New("user is not the user to be deleted or user to delete is superuser")
	}

}
