// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"intelligent-course-aware-ide/api/chat"
	chatLogic "intelligent-course-aware-ide/internal/logic/chat"
	chatMessageLogic "intelligent-course-aware-ide/internal/logic/chatMessage"
	loginLogic "intelligent-course-aware-ide/internal/logic/login"
)

type ControllerV1 struct {
	chats        chatLogic.Chats
	chatMessages chatMessageLogic.ChatMessages
	logins       loginLogic.Logins
}

func NewV1() chat.IChatV1 {
	return &ControllerV1{
		chats:        *chatLogic.New(),
		chatMessages: *chatMessageLogic.New(),
		logins:       *loginLogic.New(),
	}
}
