// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package comment
import (
	"intelligent-course-aware-ide/internal/dao"
	"intelligent-course-aware-ide/internal/model/do"
	"intelligent-course-aware-ide/internal/model/entity"

	"context"
)
func CheckUserHasPermissionOfComment(ctx context.Context, userId int64) bool {
	var comment *entity.Comment
	err := dao.Comment.Ctx(ctx)
}