// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package example

import (
	"intelligent-course-aware-ide/api/example"
)

type ControllerV1 struct{}

func NewV1() example.IExampleV1 {
	return &ControllerV1{}
}
