
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:Y:123456@tcp(127.0.0.1:3306)/mysqlTest"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app

  logger:
    level: "all"  # "error", "debug", etc.
    stdout: true  # 输出到标准输出
    path: "./logs"

  upload:
    path: "./uploads"