name: team_project_25spring_15

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-update:
    name: Ensure PR is up-to-date with main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure PR branch is up to date with main
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main
          BASE=$(git merge-base HEAD origin/main)
          LATEST=$(git rev-parse origin/main)
          if [ "$BASE" != "$LATEST" ]; then
            echo "Your branch is behind 'main'. Please pull/rebase before pushing."
            exit 1
          fi

  go-syntax-check:
    name: Go Syntax & Format Check
    runs-on: ubuntu-latest
    needs: check-update

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Go format check (go fmt)
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [[ -n "$UNFORMATTED" ]]; then
            echo "The following files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Go vet
        working-directory: Backend/intelligent-course-aware-ide
        run: go vet ./...

      - name: Go build (optional)
        working-directory: Backend/intelligent-course-aware-ide
        run: go build ./...
      
      - name: Go lint check (optional)
        working-directory: Backend/intelligent-course-aware-ide
        run: golint ./...