name: team_project_25spring_15

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Go Syntax & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Ensure PR branch is up to date with main
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main
          BASE=$(git merge-base HEAD origin/main)
          LATEST=$(git rev-parse origin/main)
          if [ "$BASE" != "$LATEST" ]; then
            echo "❌ Your branch is behind 'main'. Please pull/rebase before pushing."
            exit 1
          fi

      - name: Go format check (go fmt)
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [[ -n "$UNFORMATTED" ]]; then
            echo "❌ The following files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Go build (optional)
        run: go build ./...

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.56.2
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: golangci-lint run ./...
