name: team_project_25spring_15

on:
  push:
    branches: [main, ope]
  pull_request:
    branches: [main, ope]

jobs:
  go-syntax-check:
    name: Go Syntax & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Go format check (go fmt)
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [[ -n "$UNFORMATTED" ]]; then
            echo "The following files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Go vet
        working-directory: Backend/intelligent-course-aware-ide
        run: go vet ./...

      - name: Go build (optional)
        working-directory: Backend/intelligent-course-aware-ide
        run: go build ./...
      
      - name: Install golint
        run: |
          go install golang.org/x/lint/golint@latest

      - name: Go lint check (optional)
        working-directory: Backend/intelligent-course-aware-ide
        run: golint ./...
  
  call-deploy:
    name: Trigger Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/ope'
    needs: go-syntax-check
    uses: ./.github/workflows/cd.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}